### ISSUE TITLE
What's the official repo?

### ISSUE THREAD

**Issue by angelf** [technoweenie/sentry#2]
What's the repo that's used to build the 'sentry' gem? The gem only points to http://techno-weenie.net/ but technoweenie/sentry doesn't have the same version that the Gem.

It would be good to update the Gem homepage but also to point to the 'official' repo from technoweenie/sentry description.

Thanks!

**Comment by technoweenie** [comment]
this lib is like 4 years old, I didn't think anyone used it :)  I may just have to setup a quickie page on technoweenie.github.com.

**Comment by angelf** [comment]
Apparently someone is updating the gem, there is a November 2, 2009 version. 
:-)

**Comment by technoweenie** [comment]
The sentry network graph says its at http://github.com/stderr/sentry

**Comment by angelf** [comment]
Ok. Thanks.
